### ISSUE TITLE
Glossary support for IndicTrans2 model

### ISSUE THREAD

**Issue by Surya291** [project-anuvaad/anuvaad#716]
Hello Team project-anuvaad, appreciate your efforts thoroughly.  
I have been exploring to setup an in-house translation engine using IndicTrans2 models released by AI4B and have been successful in that. Additionally I want to use glossary support as being used in anuvaad portal. 

I have been told that the glossary feature has been developed under anuvaad and is not part of IndicTrans2. I tried but failed finding the appropriate glossary service in the "anuvaad" repo. It'd great if you can point me the appropriate source code for the same.

**Comment by aravinth** [comment]
Hi @Surya291 : The glossary is part of the anuvaad-translator microservice.
https://github.com/project-anuvaad/anuvaad/blob/master/anuvaad-etl/anuvaad-translator/translator/tmx/tmxservice.py
