### ISSUE TITLE
[Question] How to self host?

### ISSUE THREAD

**Issue by Tejaswgupta** [project-anuvaad/anuvaad#843]
Appreciate the great work , I went through the codebase a couple of times but I can't seem to figure out the steps for self hosting. There are no related docs either and the docker files seems fragmented. Any chance someone can provide the steps to self host it or it's not supposed to be self hosted?

Thank you for your response.

**Comment by xiaoyao9184** [comment]
use this https://hub.docker.com/u/anuvaadio?

**Comment by aravinth** [comment]
@Tejaswgupta : Thanks a lot for your interest. We will work towards a streamlined process for the open source community to start contributing to Anuvaad. We have opened Discussions forum : https://github.com/project-anuvaad/anuvaad/discussions
Stay tuned for the detailed documentation of the setup. Until that you can familiarise yourself with the following materials : 

Anuvaad Homepage : https://www.anuvaad.org/
Youtube Tutorials : https://www.youtube.com/@project-anuvaad/playlists
Workbench Link : http://users.anuvaad.org/
GitHub Repo : https://github.com/project-anuvaad/anuvaad
Wiki : https://github.com/project-anuvaad/anuvaad/wiki
